def get_project_custom_fields():
	'''
		Method to get custom fields for Project doctype
	'''
	return {
		"Project": [
			{
				"fetch_from": "project_template.category_type",
				"fetch_if_empty": 0,
				"fieldname": "category_type",
				"fieldtype": "Link",
				"in_list_view": 1,
				"insert_after": "custom_project_service",
				"label": "Category Type",
				"options": "Category Type",
				"read_only": 1,
				"reqd": 1,
			},
			{
				"fieldname": "compliance_agreement",
				"fieldtype": "Link",
				"insert_after": "category_type",
				"label": "Compliance Agreement",
				"options": "Compliance Agreement",
				"read_only": 1,
			},
			{
				"fetch_from": "project_template.compliance_category",
				"fetch_if_empty": 0,
				"fieldname": "compliance_category",
				"fieldtype": "Link",
				"insert_after": "project_template",
				"label": "Compliance Category",
				"options": "Compliance Category",
			},
			{
				"fetch_from": "project_template.compliance_sub_category",
				"fetch_if_empty": 0,
				"fieldname": "compliance_sub_category",
				"fieldtype": "Link",
				"insert_after": "compliance_category",
				"label": "Compliance Sub Category",
				"options": "Compliance Sub Category",
			},
			{
				"depends_on": "eval:doc.custom_is_internal == 0",
				"fieldname": "custom_billing_instruction",
				"fieldtype": "Long Text",
				"insert_after": "custom_instructions",
				"label": "Billing Instruction",
				"read_only": 1,
			},
			{
				"fieldname": "custom_instructions",
				"fieldtype": "Long Text",
				"insert_after": "hold",
				"label": "Instructions",
			},
			{
				"fieldname": "custom_is_internal",
				"fieldtype": "Check",
				"insert_after": "project_supervisor",
				"label": "Is Internal",
				"read_only": 1,
			},
			{
				"fieldname": "custom_project_service",
				"fieldtype": "Data",
				"insert_after": "custom_sub_category_name",
				"label": "Project Service",
			},
			{
				"fetch_from": "compliance_sub_category.sub_category",
				"fetch_if_empty": 0,
				"fieldname": "custom_sub_category_name",
				"fieldtype": "Data",
				"in_list_view": 1,
				"insert_after": "compliance_sub_category",
				"label": "Sub Category Name",
			},
			{
				"fetch_from": "customer.customer_name",
				"fetch_if_empty": 1,
				"fieldname": "customer_name",
				"fieldtype": "Data",
				"insert_after": "column_break_14",
				"label": "Customer Name",
			},
			{
				"fieldname": "hold",
				"fieldtype": "Check",
				"hidden": 1,
				"insert_after": "site_location",
				"label": "Hold",
				"read_only": 1,
			},
			{
				"fieldname": "is_invoiced",
				"fieldtype": "Check",
				"insert_after": "message",
				"label": "Is Invoiced",
			},
			{
				"fieldname": "project_supervisor",
				"fieldtype": "Link",
				"insert_after": "department",
				"label": "Supervisor",
				"options": "User",
			},
			{
				"fieldname": "site_location",
				"fieldtype": "Link",
				"insert_after": "percent_complete",
				"label": "Site Location",
				"options": "Location",
			},
			{
				"fieldname": "renew_email_sent_on",
				"fieldtype": "Date",
				"label": "Renew Email Sent On",
				"hidden": 1,
				"insert_after": "is_invoiced",
			},
			{
				"fieldname": "is_premium",
				"fieldtype": "Check",
				"label": "Is Premium",
				"read_only": 1,
				"insert_after": "custom_is_internal",
			},
		]
	}
