def get_customer_property_setters():
	'''
		Get property setters for Customer doctype.
	'''
	return [
		{
			"doc_type": "Customer",
			"doctype_or_field": "DocField",
			"field_name": "column_break1",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Customer",
			"doctype_or_field": "DocField",
			"field_name": "customer_type",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Customer",
			"doctype_or_field": "DocType",
			"property": "quick_entry",
			"property_type": "Check",
			"value": "0",
		},
		{
			"doc_type": "Customer",
			"doctype_or_field": "DocField",
			"field_name": "internal_customer_section",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Customer",
			"doctype_or_field": "DocField",
			"field_name": "naming_series",
			"property": "reqd",
			"property_type": "Check",
			"value": "0",
		},
		{
			"doc_type": "Customer",
			"doctype_or_field": "DocField",
			"field_name": "naming_series",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Customer",
			"doctype_or_field": "DocField",
			"field_name": "account_manager",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Customer",
			"doctype_or_field": "DocField",
			"field_name": "sales_team_tab",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Customer",
			"doctype_or_field": "DocField",
			"field_name": "default_price_list",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Customer",
			"doctype_or_field": "DocField",
			"field_name": "loyalty_program",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Customer",
			"doctype_or_field": "DocField",
			"field_name": "so_required",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Customer",
			"doctype_or_field": "DocField",
			"field_name": "dn_required",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Customer",
			"doctype_or_field": "DocField",
			"field_name": "customer_primary_contact",
			"property": "fetch_from",
			"property_type": "Small Text",
			"value": "",
		},
		{
			"doc_type": "Customer",
			"doctype_or_field": "DocField",
			"field_name": "naming_series",
			"property": "options",
			"property_type": "Text",
			"value": "CUST-.YYYY.-",
		},
	]
