def get_sales_order_item_property_setters():
	'''
		Get property setters for Sales Order Item doctype.
	'''
	return [
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "amount",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "net_rate",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "net_amount",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "base_net_rate",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "base_net_amount",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "delivery_date",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "0",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "delivery_date",
			"property": "depends_on",
			"property_type": "Data",
			"value": "",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "delivery_date",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "description",
			"property": "allow_on_submit",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "drop_ship_section",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "grant_commission",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "inter_transfer_reference_section",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "is_free_item",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "item_code",
			"property": "columns",
			"property_type": "Int",
			"value": "2",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "item_code",
			"property": "label",
			"property_type": "Data",
			"value": "Service",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "item_weight_details",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "manufacturing_section_section",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "planning_section",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "qty",
			"property": "default",
			"property_type": "Text",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "qty",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "section_break_63",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "shopping_cart_section",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "warehouse_and_reference",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order Item",
			"doctype_or_field": "DocField",
			"field_name": "warehouse",
			"property": "in_list_view",
			"property_type": "Check",
			"value": "0",
		},
	]
