def get_sales_order_property_setters():
	'''
		Get property setters for Sales Order doctype.
	'''
	return [
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "additional_info_section",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "discount_amount",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "additional_discount_percentage",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "apply_discount_on",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "base_net_total",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "base_grand_total",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "base_in_words",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "grand_total",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "rounded_total",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "in_words",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "base_discount_amount",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "base_rounded_total",
			"property": "allow_on_submit",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "base_rounded_total",
			"property": "hidden",
			"property_type": "Check",
			"value": "0",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "base_rounded_total",
			"property": "print_hide",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "custom_expected_end_date",
			"property": "in_list_view",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "delivery_date",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "delivery_date",
			"property": "in_list_view",
			"property_type": "Check",
			"value": "0",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "delivery_status",
			"property": "in_standard_filter",
			"property_type": "Check",
			"value": "0",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "disable_rounded_total",
			"property": "default",
			"property_type": "Text",
			"value": "0",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "due_date",
			"property": "print_hide",
			"property_type": "Check",
			"value": "0",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "grand_total",
			"property": "in_list_view",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "in_words",
			"property": "hidden",
			"property_type": "Check",
			"value": "0",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "in_words",
			"property": "print_hide",
			"property_type": "Check",
			"value": "0",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "incoterm",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "items",
			"property": "label",
			"property_type": "Data",
			"value": "Services",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocType",
			"property": "default_print_format",
			"property_type": "Data",
			"value": "Sales Order New",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocType",
			"property": "field_order",
			"property_type": "Data",
			"value": '["workflow_state", "customer_section", "column_break0", "title", "naming_series", "customer", "customer_name", "tax_id", "order_type", "column_break_7", "transaction_date", "custom_billing_date", "delivery_date", "column_break1", "po_no", "po_date", "company", "skip_delivery_note", "is_reverse_charge", "is_export_with_gst", "is_rework", "amended_from", "accounting_dimensions_section", "cost_center", "dimension_col_break", "project", "currency_and_price_list", "currency", "conversion_rate", "column_break2", "selling_price_list", "price_list_currency", "plc_conversion_rate", "ignore_pricing_rule", "sec_warehouse", "scan_barcode", "custom_create_project_automatically", "column_break_28", "set_warehouse", "reserve_stock", "items_section", "items", "section_break_31", "total_qty", "total_net_weight", "column_break_33", "base_total", "base_net_total", "column_break_33a", "total", "net_total", "custom_section_break_rlk6s", "custom_billing_instruction", "custom_section_break_siqmb", "custom_project_name_automatically", "custom_project_name", "custom_expected_start_date", "custom_assign_to", "custom_column_break_nhc2l", "custom_expected_end_date", "custom_priority", "taxes_section", "tax_category", "taxes_and_charges", "column_break_38", "shipping_rule", "column_break_49", "incoterm", "named_place", "section_break_40", "taxes", "section_break_43", "base_total_taxes_and_charges", "column_break_46", "total_taxes_and_charges", "totals", "base_grand_total", "base_rounding_adjustment", "base_rounded_total", "base_in_words", "column_break3", "grand_total", "rounding_adjustment", "rounded_total", "in_words", "advance_paid", "disable_rounded_total", "section_break_48", "apply_discount_on", "base_discount_amount", "coupon_code", "column_break_50", "additional_discount_percentage", "discount_amount", "sec_tax_breakup", "other_charges_calculation", "section_gst_breakup", "gst_breakup_table", "packing_list", "packed_items", "pricing_rule_details", "pricing_rules", "contact_info", "billing_address_column", "customer_address", "address_display", "billing_address_gstin", "gst_category", "place_of_supply", "customer_group", "territory", "column_break_84", "contact_person", "contact_display", "contact_phone", "contact_mobile", "contact_email", "shipping_address_column", "shipping_address_name", "shipping_address", "column_break_93", "dispatch_address_name", "dispatch_address", "col_break46", "company_address", "company_gstin", "column_break_92", "company_address_display", "payment_schedule_section", "custom_bank_details", "custom_bank", "custom_account_name", "custom_account_no", "custom_column_break_10jvv", "custom_branch_code", "custom_branch", "payment_terms_section", "payment_terms_template", "payment_schedule", "terms_section_break", "tc_name", "terms", "more_info", "section_break_78", "status", "delivery_status", "per_delivered", "column_break_81", "per_billed", "per_picked", "billing_status", "sales_team_section_break", "sales_partner", "column_break7", "amount_eligible_for_commission", "commission_rate", "total_commission", "section_break1", "sales_team", "loyalty_points_redemption", "loyalty_points", "column_break_116", "loyalty_amount", "subscription_section", "from_date", "to_date", "column_break_108", "auto_repeat", "update_auto_repeat_reference", "printing_details", "letter_head", "group_same_items", "column_break4", "select_print_heading", "language", "additional_info_section", "is_internal_customer", "represents_company", "column_break_152", "source", "inter_company_order_reference", "campaign", "party_account_currency", "custom_reimbursement", "custom_reimbursement_details_", "custom_reimbursement_details", "custom_total_reimbursement_amount", "connections_tab", "gst_section", "gst_col_break", "ecommerce_supply_type", "ecommerce_gstin"]',
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "naming_series",
			"property": "default",
			"property_type": "Text",
			"value": "SAL-ORD-.YYYY.-",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "naming_series",
			"property": "options",
			"property_type": "Text",
			"value": "SAL-ORD-.YYYY.-",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "order_type",
			"property": "read_only",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "payment_schedule",
			"property": "print_hide",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "per_billed",
			"property": "in_list_view",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "po_no",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "rounded_total",
			"property": "hidden",
			"property_type": "Check",
			"value": "0",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "rounded_total",
			"property": "print_hide",
			"property_type": "Check",
			"value": "0",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "scan_barcode",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "set_warehouse",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "shipping_rule",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "status",
			"property": "in_list_view",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "status",
			"property": "options",
			"property_type": "Text",
			"value": "\nDraft\nOn Hold\nTo Deliver and Bill\nTo Bill\nTo Deliver\nCompleted\nCancelled\nClosed\nProforma Invoice",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "subscription_section",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "tax_id",
			"property": "hidden",
			"property_type": "Check",
			"value": "0",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "tax_id",
			"property": "print_hide",
			"property_type": "Check",
			"value": "0",
		},
		{
			"doc_type": "Sales Order",
			"doctype_or_field": "DocField",
			"field_name": "total_qty",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
	]
