def get_task_property_setters():
	'''
		Get property setters for Task doctype.
	'''
	return [
		{
			"doc_type": "Task",
			"doctype_or_field": "DocField",
			"field_name": "parent_task",
			"property": "read_only",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocField",
			"field_name": "task_weight",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocType",
			"property": "field_order",
			"property_type": "Data",
			"value": '["subject", "project", "project_name", "category_type", "customer", "issue", "type", "compliance_sub_category", "column_break0", "status", "priority", "task_weight", "parent_task", "assigned_to", "completed_by", "completed_on", "custom_serial_number", "color", "is_group", "is_template", "hold", "custom_is_payable", "custom_document_checklist", "custom_task_document_items", "custom_payment_info", "custom_payable_amount", "custom_mode_of_payment", "custom_column_break_hrdgn", "custom_reference_number", "custom_reference_date", "custom_user_remark", "sb_timeline", "exp_start_date", "expected_time", "start", "column_break_11", "exp_end_date", "progress", "duration", "is_milestone", "sb_details", "description", "sb_depends_on", "depends_on", "depends_on_tasks", "sb_actual", "act_start_date", "actual_time", "column_break_15", "act_end_date", "sb_costing", "total_costing_amount", "total_expense_claim", "column_break_20", "total_billing_amount", "sb_more_info", "review_date", "closing_date", "column_break_22", "department", "company", "lft", "rgt", "old_parent", "template_task"]',
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocType",
			"property": "sort_order",
			"property_type": "Data",
			"value": "ASC",
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocType",
			"property": "sort_field",
			"property_type": "Data",
			"value": "custom_serial_number",
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocField",
			"field_name": "customer",
			"property": "in_list_view",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocField",
			"field_name": "is_milestone",
			"property": "in_list_view",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocField",
			"field_name": "priority",
			"property": "in_list_view",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocField",
			"field_name": "status",
			"property": "in_list_view",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocField",
			"field_name": "is_group",
			"property": "in_list_view",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocField",
			"field_name": "project",
			"property": "in_list_view",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocField",
			"field_name": "subject",
			"property": "in_list_view",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocField",
			"field_name": "status",
			"property": "options",
			"property_type": "Select",
			"value": "Open\nWorking\nPending Review\nOverdue\nTemplate\nHold\nCompleted\nCancelled",
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocField",
			"field_name": "type",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocField",
			"field_name": "issue",
			"property": "hidden",
			"property_type": "Check",
			"value": "1",
		},
		{
			"doc_type": "Task",
			"doctype_or_field": "DocField",
			"field_name": "sb_timeline",
			"property": "depends_on",
			"property_type": "Data",
			"value": "",
		},
	]
